### ISSUE TITLE
Optimise storagesc smart contract.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#104]
# storagesc

Make sure interest rate, and earnings are correct for a delegate and stakers based on write and read price, slash rate, and they get rewarded min_demand even if client does not put any storage. Also try to optimize the smart contract code for faster execution, especially when there is invalid data such as bad ID (allocation, wallet, etc)

1. Does blobber delegate receive all the storage earnings and interest based on their period. When do they receive it? Can they unstake, and if so, how much?
2. Is the storage earnings and interest received correct? How do you verify?
3. Does blobber delegate receive service charge even if he does not stake? Is it just based on storage earnings?
4. Does a client who stakes on a blobber receive storage earnings minus slashes and minus the service charge? Is the interest affected by slashes or service charge?
5. Lets say we have 2 clients, and they have unequal stake, do they receive proportionate storage earnings minus slashes and minus service charge. What about interest?
6. Are the storage earnings correct based on write and read price and slash rate? Do the blobbers receive min_demand even if client does not put any storage? 
7. When allocation expires does all tokens go to the blobber?
8.  When client cancels allocation due to failed challenges, do all the tokens go back to the client?
9. Is the staking separate for validator or they go to the blobber delegate wallet and clients who stake for blobbers.

**Comment by Sriep** [comment]
Benchmark tests with 1000 miners and 1000 sharders done by a previous developer - in GitHub (find link)

#### Notes from the developer: 
Just tested how fast the transactions for 1000 blobbers. It was 141ms. The databases were empty. If we load them with something transactions will take even more time. And those tests were on a synthetic system, not the real one so the real one could even longer on empty blobbers. With loaded blobbers, it could take approximately 300-500ms.

We tested challenges. Here is the result
generateChallenges 344.41 ms/op
Did that
using: challenge_rate_per_mb_min: 1
max_challenges_per_generation: 100

For challenge_response it took 20ms and in this case, it does not matter how many allocaitons/blobbers/validators we used. Test parameters were data_shards=10 parity_shards=10


<img width="911" alt="Screen Shot 2020-12-30 at 1 21 55 PM" src="https://user-images.githubusercontent.com/6240686/110920565-724af900-8315-11eb-902a-23c4638821a2.png">

**Comment by Sriep** [comment]
Unit test for payments/fees. 

[blobber_test.go](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/smartcontract/storagesc/blobber_test.go) seems to check the various fee/payment values. However, it does it for just one example for each case. The example's parameters hidden by liberal use of magic numbers.

I am creating a new test, effectively reusing much of blobber_main_test.go:
* Nested loops for each input parameter.
* Calculate the expected amounts outside of storagesc in easily accessible code.
* Confirm that storagesc methods reproduce the same values.

**Comment by bbist** [comment]
@peterlimg, @guruhubb,

We could overhaul current MPT implementation to optimize for all performance gains we could tap so that there's no overhead caused by MPT access. Some optimizations include:
1. Replace Serializable interface with { hash: []byte, value: []byte } data type, once a value is inserted into MPT. Right now there are multiple Encode(), GetHashBytes() operations that does repeated encoding and hashing. Doing it only once would give us a lot of performance gain.
2. I think effectively using LevelNodeDB + MemoryNodeDB would helps us do away with ChangeCollector, which at its current form is not very optimal. First because of above mentioned reason, second because it accumulates multiple redundant changes that'll never be part of MPT.
3. ValueNode is unnecessary. Value can be made part of LeafNode directly.
4. Origin field is unnecessary.
5. With better API for getting multiple nodes at once, many MPT read operations can be combined into one. With this we could also properly normalize the data items we store in MPT for different smart contracts.
6. Having separate method to only read node metadata (origin tracker) information. This could be used to extract subtree with specific version. This could be used to change state pruning from very costly mark-and-sweep to static, oldest round first.
And there are many more optimizations that could be done.

Fixing MPT and making it as efficient as possible would help us significantly improve performance. And in case some smart contracts turn out to be fundamentally slow by design, we can work on them one by one.

**Comment by Sriep** [comment]
Converted into separate issues plus benchamrking app.
