### ISSUE TITLE
Fix lint errors reported by golangci-lint

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#111]
https://github.com/0chain/0chain/runs/2105194893

**Comment by guruhubb** [comment]
Is this same as #132 @Sriep ?

**Comment by MurashovVen** [comment]
In this case, the problem is that the linter preparation process crashes because of `c` dependences. I fixed it in [PR](https://github.com/0chain/0chain/pull/184), but the linter checks still fail because the project code currently does not corresponds to the linter requirements.

I think we need to solve all the problems the linter is messaging, and then enable checks.

**Comment by Sriep** [comment]
This is the same issue as https://github.com/0chain/0chain/issues/132

**Comment by Sriep** [comment]
Fixed in https://github.com/0chain/0chain/pull/184. Will need to handle merge conflicts due to https://github.com/0chain/0chain/pull/162.
Recommend fixing issue https://github.com/0chain/0chain/issues/202 before activating this functionality.

**Comment by Sriep** [comment]
Issue moved to https://github.com/0chain/0chain/issues/202. To be picked up when 202 resolved.
