### ISSUE TITLE
Slow MPT iterating

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1210]
This problem happens after hightps-2 worked more than a week, causing it to stuck
```
2022-04-27T13:33:50.616Z	ERROR	chain/worker.go:515	Sync round state abort, context timed out for checking missing nodes
0chain.net/chaincore/chain.(*Chain).syncRoundStateToStateDB
	/0chain/go/0chain.net/chaincore/chain/worker.go:515
0chain.net/chaincore/chain.(*Chain).SyncLFBStateWorker.func2
	/0chain/go/0chain.net/chaincore/chain/worker.go:465
2022-04-27T13:33:50.616Z	ERROR	util/merkle_patricia_trie.go:986	Find missing node with unexpected err	{"error": "context deadline exceeded"}
0chain.net/core/util.(*MerklePatriciaTrie).FindMissingNodes
	/0chain/go/0chain.net/core/util/merkle_patricia_trie.go:986
0chain.net/chaincore/chain.(*Chain).syncRoundStateToStateDB
	/0chain/go/0chain.net/chaincore/chain/worker.go:508
0chain.net/chaincore/chain.(*Chain).SyncLFBStateWorker.func2
	/0chain/go/0chain.net/chaincore/chain/worker.go:465
2022-04-27T13:33:50.616Z	ERROR	util/merkle_patricia_trie.go:808	iterate - child node	{"error": "context deadline exceeded"}
0chain.net/core/util.(*MerklePatriciaTrie).iterate
	/0chain/go/0chain.net/core/util/merkle_patricia_trie.go:808
0chain.net/core/util.(*MerklePatriciaTrie).Iterate
	/0chain/go/0chain.net/core/util/merkle_patricia_trie.go:292
0chain.net/core/util.(*MerklePatriciaTrie).FindMissingNodes
	/0chain/go/0chain.net/core/util/merkle_patricia_trie.go:980
0chain.net/chaincore/chain.(*Chain).syncRoundStateToStateDB
	/0chain/go/0chain.net/chaincore/chain/worker.go:508
0chain.net/chaincore/chain.(*Chain).SyncLFBStateWorker.func2
	/0chain/go/0chain.net/chaincore/chain/worker.go:465
```

**Comment by peterlimg** [comment]
The iteration will always timeout when the database become large, we need to have a better way to detect missing states.

**Comment by peterlimg** [comment]
The iteration timeout does not cause the BC stuck, instead, it is the blockchain stuck that trigger the state syncing process. Then we will see this timeout error because the MPT state is too big, the iteration could not be finished in given time. I'm thinking if this sync is necessary now, as when MPT becomes large, this iteration will always timeout. It can not help on recovering the BC anymore. So I think perhaps we can remove this whole MPT scanning process. @dabasov

**Comment by peterlimg** [comment]
The client state prune process will do the whole MPT iteration to a) update node version to current round number b) delete all nodes below specific round. Both the a) and b) will be a problem when the MPT is large. 

For testing server that currently has 1.5 million rounds, the prune update process takes more than 10 seconds in average, and 6 seconds for deleting process. Since The `MPT.iteration` will stop the writing access, so for the prune update version process, it will stop the MPT writing for about 10 seconds periodically.

**Comment by peterlimg** [comment]
Fixed
