### ISSUE TITLE
collected_reward needs input parameters untangled

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#1354]
collected_reward REST API expects start_block, end_block and client_id as filters, while the SQL query uses clinetId, PoolId, ProviderType and ProviderId in its where clause . I am not sure what filters we actually want to use. (edited)

**Comment by lawRathod** [comment]
The endpoint only supports the `start/end block` and `client_id`  because that's all that are needed at the moment and if we need the others someone will ask. 

To confirm if the where clause has empty values with `AND` operator, I tried to debug and it seems gorm doesn't include the undefined fields in a struct ⬇️ . While everything defined is part of the where clause, which I think is desired. 

![image](https://user-images.githubusercontent.com/31697445/180050599-3c7a63d6-91b9-44ff-b998-eb2cc5c9b253.png)

**Comment by Sriep** [comment]
I think it could just be a matter of code quality, as there are confusing variables that are never used.
