### ISSUE TITLE
Calling /v1/chain/get on sharder without an id results in nil pointer

### ISSUE THREAD

**Issue by stewartie4** [0chain/0chain#1546]
sharder:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/18306778/181996513-7f83d362-6f7a-4908-822a-ee975875d932.png">
vs miner:
<img width="575" alt="image" src="https://user-images.githubusercontent.com/18306778/181996525-b5d66670-18c4-49df-ac81-659b29ff55c1.png">

**Comment by boddumanohar** [comment]
@dabasov 

I tried to debug this, the error is actually coming from: 

both `sharders` and `miners` are using [handlersMap](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/handler.go#L42) to initialise handlers. 

when `/v1/chain/get` endpoint is accessed, [memorystore.WithConnectionHandler](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/handler.go#L47) function is called which inturn gets a connection from the Redis connection pool. 

But we using Redis in only miner but not shaders. 

Since Redis is not initialised during sharder start, and when this API is called we are getting a panic.

**Comment by boddumanohar** [comment]
@dabasov  as a fix for the above issue, I've raised a PR https://github.com/0chain/0chain/pull/1630 that removes `/v1/chain/get` on sharder. Would that suffice to fix the issue?

**Comment by boddumanohar** [comment]
fixed by: https://github.com/0chain/0chain/pull/1630
