### ISSUE TITLE
Update `spUpdate.DelegateRewards` to currency.Coin

### ISSUE THREAD

**Issue by 0xhrsh** [0chain/0chain#1577]
[Context Here](https://github.com/0chain/0chain/pull/1509#discussion_r923963494)

**Comment by peterlimg** [comment]
Blocked by issue 0chain/0chain#2122

**Comment by boddumanohar** [comment]
At the moment `DelegateRewards` can be positive or negative. A Positive value implies a reward. A negative values implies a penality. Negative value would lead to uint64 overflow of currency.Coin. I would suggest to leave it as int64 at the moment. Otherwise, we will need to add a new field to indicate whether it's a reward or a penalty, code for updating reward of event db will also need to updated.

**Comment by boddumanohar** [comment]
completed by: https://github.com/0chain/0chain/pull/1870
