### ISSUE TITLE
Do not expose the panic stack info to user

### ISSUE THREAD

**Issue by Dmdv** [0chain/0chain#1608]
https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/core/common/mdw_recover.go#L32

```golang
	return func(w http.ResponseWriter, r *http.Request) {
		defer func() {
			if err := recover(); err != nil {
				logging.Logger.Error("panic handling message",
					zap.Any("error", err),
					zap.String("remote address", r.RemoteAddr),
					zap.String("method", r.Method),
					zap.String("request uri", r.RequestURI),
				)
				w.Header().Set("Content-Type", "application/json")
				data := make(map[string]interface{}, 2)
				data["error"] = fmt.Sprintf("%v", err)
				if are, ok := err.(*Error); ok {
					data["code"] = are.Code
				}

```

**Comment by devyetii** [comment]
The `error` variable is transformed into just an error message with `fmt.Sprintf("%v", err)` since `error` interface in go is required to implement `Error` method that returns this error message as string. However, I'll add an extra check for some keywords like `panic` and `stack trace` where if found in the default error message should return a generic error message e.g. "Unknown Server Error"
