### ISSUE TITLE
Issue with summation of total challenges

### ISSUE THREAD

**Issue by sagchain** [0chain/0chain#1645]
Total challenges = Passed + Failed but I am getting Total challenges = Open + Passed + Failed. 

A challenge should not remain open for an indefinite period is my understanding.  In the data we are seeing open challenges from past week as well

**Comment by lawRathod** [comment]
The endpoints in most cases will only have approximate data. What is the deviation from passed+failed and total-challenges are you noticing?

**Comment by Sriep** [comment]
There is no way to distinguish between open and failed for challenges that have not been responded to. The point here is that challenges fail silently. 

Round 500: We have 5 open challenges no failed challenges. One of the challenges expires in 0.3 seconds.
Round 501: We have 4 open challenges and one challenge that expired 0.7 seconds ago. 

There is no easy way to distinguish between round 500 and round 501 without a time-consuming examination of every challenge. Or scheduling a transaction to run each time a challenge expires - we have not implemented a mechanism to do this.

When a user selects a point and we retrieve the individual challenges for that point. Then it is easy to make the distinction. 

 I suggest working round the issue rather than tackling it head on.

**Comment by guruhubb** [comment]
@avanaur can you work on this. @dabasov this needs to be done on the blobber repo as a table

**Comment by dabasov** [comment]
@guruhubb how can this information can be trusted? btw, we do not provide user rest api from blobber side

**Comment by Sriep** [comment]
I think this has already been done. Please reopen if not.
