### ISSUE TITLE
any request will be blocked if there is a custom request header

### ISSUE THREAD

**Issue by cnlangzi** [0chain/0chain#1672]
see detail [here](https://0chain.slack.com/archives/C02PLQHMPNG/p1663203281515279?thread_ts=1662983338.504689&cid=C02PLQHMPNG) and [here](https://0chain.slack.com/archives/C03788G8N2D/p1662450670102839?thread_ts=1662428994.573279&cid=C03788G8N2D)

**Comment by manasnisar** [comment]
@dabasov As clarified by @cnlangzi this issue was related to rate limiting and separate from the CORS issue on k8s, the rate-limiting is working as expected, however, there may be some fix needed on Nginx as pointed out [here](https://0chain.slack.com/archives/C01GMABG2T1/p1665475267220539?thread_ts=1665192706.542649&cid=C01GMABG2T1)

**Comment by manasnisar** [comment]
@dabasov  There haven't been any instances of this lately. Should we close this?

**Comment by cnlangzi** [comment]
report it again on https://0chain.slack.com/archives/C03788G8N2D/p1673484382690979
