### ISSUE TITLE
Authorize users to update allocation

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#1825]
Any user should be able to Extend size and expiry of an arbitrary allocation.

this check in `updateAllocationRequestInternal` should be changed
https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/smartcontract/storagesc/allocation.go#L1097:L1100

**Comment by guruhubb** [comment]
Owner can `disable` allowing anyone to extend size and expiry of allocation @peterlimg

**Comment by guruhubb** [comment]
This issue can be done in combination with https://github.com/0chain/0chain/issues/828 by enabling user to have the option to disable update by others. The default is to allow others to extend expiry and size.

**Comment by devyetii** [comment]
@guruhubb According to my investigation of #828 till now, I think it has to do also with the "blobber" repo as the actual worker which should actually prevent update/rename/copy/move action according to the settings the user entered for the allocation. The "blobber" here is the backend, whereas "zboxcli" acts as the Frontend or the client side so I think, since it also has access to the allocation, we should add a check there as well to avoid sending unnecessary requests.

**Comment by devyetii** [comment]
The changes related to this issue are applied in the PR on the issue #828 (!1877)
