### ISSUE TITLE
Charts data needed for Atlus (AMA)

### ISSUE THREAD

**Issue by sagchain** [0chain/0chain#1859]
Require data/end points for all the below charts:

Market charts:
1) Total Value Locked  
2) Total Allocated Storage Value Locked

Network charts:
1) Transactions per day  
2) Utilization %  
3) Network-Wide Quality Score  
4) Unique addresses  
5) Block Count Charts  
6) Daily Average Transaction Fee

Storage charts:
1) Average Write Price  
2) Top Blobbers by Total Allocated Storage (TB)  
3) Network-wide Daily Allocations

**Comment by dabasov** [comment]
Market
1. Total Value Locked - we have one
2. AllocatedStorage * AverageWritePrice

Network
currently we add block to the events_db on every block addition to blockchain, check this https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/sharder/sharder/sharder.go#L151
we need to add similar handler for `OnFinalized()`and update current block on finalization. We need it, because all stats should be computed only for finalized blocks. also this might not work well https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/block/block_eventdb.go#L32
1. Add new aggregate, update it on every finalized block on amount of transactions in current block
2. UsedStorage/AllocatedStorage ?
3. SuccessfulChallenges/TotalChallenges
4. Add new aggregate, update on every change of balance nonce from 0 to 1, https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/state.go#L652 we can emit new event here
5. New aggregate, update on new block being finalized
6. New aggregate, update with sum txn.fee for every transaction in the block

Storage:
1. AverageWritePrice
2. BlobberAggregate.RankMetric
3. AllocatedStorage ?

**Comment by manasnisar** [comment]
@dabasov Question: Do you mean we need to add block to events_db on finalization [here](https://github.com/0chain/0chain/blob/staging/code/go/0chain.net/chaincore/chain/protocol_block.go#L292) instead of on `addBlock`, or should we let the adding as it is and update the same on finalization?

**Comment by dabasov** [comment]
@manasnisar we can't simply add there, since this code will be called on miner and sharder both, so we better add a point of extension the same way we have for block addition. And we don't want to add it instead, we want to add one more event and update blocks that were added before in addBlock

**Comment by sagchain** [comment]
Additional comments from Saswata adding here: 

For Charts, why are Total Value Locked and Staked negative numbers? Why is storage cost so high for TB/day ? (we should be consistent and do $/TB/year). ZCN circulating supply should be coming from 0chain api. The market cap should be ZCN price x circulating supply.

The storage charts are inaccurate starting with price that I mentioned should be $/TB/month and the other two in blank for top blobbers and daily allocations.
