### ISSUE TITLE
Unit tests to check MPT consistency in SCs

### ISSUE THREAD

**Issue by Kishan-Dhakan** [0chain/0chain#2085]
- All map iterating code in Smart contracts should be thread-safe for read write and write.

**Comment by peterlimg** [comment]
@Kishan-Dhakan we don't need the thread safe as SCs are executed one by one, what we need is to avoid random map accessing, i.e. `for k, v := range aMap` when updating MPT state.

**Comment by guruhubb** [comment]
@dabasov 
Peter -> please check https://github.com/0chain/0chain/blob/b23843eb6e57429c2a78c223e0aec13a7764e34d/code/go/0chain.net/smartcontract/storagesc/challenge_test.go#L561 for example.
The things need to mention we need to setup the test data correctly to run the SC, otherwise, it may just useless, for example, if we only setup one record in a map, no matter how many times we re-run the map, it would always result in the same state root.

Despite the tests we needed, I’d like someone help to global search the map iterating code in all SCs, this can be easier to do first and fast, and I’ll also do this later in case we miss something.We need to do it with unit tests as we need to compare the state root after running the SCs.
