### ISSUE TITLE
Could not remove allocation from blobber

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#2256]
There are a lot of `could not remove allocation from blobber` errors during the miner work

**Comment by dabasov** [comment]
"adding_challenge_error: could not remove allocation from blobber: item not found:

**Comment by peterlimg** [comment]
I'll have a check and fix, should be related to one of my SC optimizations code.

**Comment by peterlimg** [comment]
We got this error because the [removeBlobber](https://github.com/0chain/0chain/blob/c5c659a002bdff68bfcea22c30f480e0288c3a2a/code/go/0chain.net/smartcontract/storagesc/models.go#L904) will remove the allocation from the blobber, while the blobber itself is not removed from the challenge ready partition, so populateChallenge function, when we try to challenge this blobber, and the allocation is selected, we will see this error. We can fix it by ignoring the allocation and continue to challenge next allocation. I'll send a PR to close it.
