### ISSUE TITLE
Maintain go.mod and go.sum as part of continuous intergration.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#233]
go.mod and go.sum are essentially generated files, and as such maintaining them is best left up to the continuous integration process.

Suggestion: Add a Github pull request / merge action that automatically updates these files.
There is a [go-mod component to the makefile](https://github.com/0chain/0chain/blob/master/Makefile#L13) which might prove useful.

**Comment by shravanshetty1** [comment]
In case of go.mod, I dont think we should do this - we want to use dependencies at a specific commit however if we were to generate go.mod file it will always use dependencies from latest commit. This can introduce breaking changes.

**Comment by Sriep** [comment]
Why do we want to use dependencies from a specific commit?

**Comment by shravanshetty1** [comment]
> Why do we want to use dependencies from a specific commit?

What if a dependency makes a breaking change? we will inherit the breaking change and our software will stop working. This is the reason why go.mod forces you to manually update dependencies. When you add a new dependency it adds the dependency from the last stable commit available at the time of adding the dependency. If new stable releases are available - you must manually update due to the above issue.

**Comment by Sriep** [comment]
We can write a script to merge the `go mod tidy` result with a manual set of exceptions. The key is to minimise developer envolvment.

**Comment by ma2b0043** [comment]
@Sriep @mohsenno1 when can we expect to close this issue?

**Comment by dabasov** [comment]
agree with @shravanshetty1 this process better left for developers
