### ISSUE TITLE
Protect memorystore.DefaultPool from concurrent access.

### ISSUE THREAD

**Issue by Sriep** [0chain/0chain#242]
Protect [memorystore.DefaultPool](https://github.com/0chain/0chain/blob/master/code/go/0chain.net/core/memorystore/connection.go#L23) from concurrent access.

This issue causes race conditions in `code/go/0chain.net/core/memorystore/store_test.go`.https://github.com/0chain/0chain/pull/218#issuecomment-832724888

**Comment by platsko** [comment]
In progress

**Comment by guruhubb** [comment]
@Sriep can you take this up as @platsko  is busy with other items

**Comment by platsko** [comment]
I researched and debugged the source code. In fact memorystore.DefaultPool is an instance of redis.Pool of the module github.com/gomodule/redigo/redis which already thread-safe because implements the concurrent access mechanism.
And the race-detecting unit tests ran with the latest version of the branch master confirm that there is no race. So, I don't think we need to fix anything there.
