### ISSUE TITLE
Cors issue in network four

### ISSUE THREAD

**Issue by haule24hdev** [0chain/0chain#269]
![Screenshot from 2021-05-12 16-43-02](https://user-images.githubusercontent.com/50743635/117955121-e61f7700-b341-11eb-9166-36f8a4b55098.png)

**Comment by haule24hdev** [comment]
Also Cors issue in network four https://four.devnet-0chain.net/blobber
![Screenshot from 2021-05-13 13-58-47](https://user-images.githubusercontent.com/50743635/118090560-e8420e00-b3f3-11eb-9672-b39084a3d65a.png)

**Comment by Sriep** [comment]
It seems to be an aspect of cybersecurity. [This blog post](https://medium.com/@dtkatz/3-ways-to-fix-the-cors-error-and-how-access-control-allow-origin-works-d97d55946d9) explains it.

The quick fix seems to be [install Moesif Origin and CORS changer](https://chrome.google.com/webstore/detail/moesif-origin-cors-change/digfbfaphojjndkpccljibejjbppifbc?hl=en-US) on your browser.

We could modify the [sever as explained here](https://flaviocopes.com/golang-enable-cors/) but that likely has security issues. There seem to be [more complicated options](https://github.com/rs/cors). Not sure if we want to do any of this?

**Comment by bbist** [comment]
@guruhubb, @haule24hdev, @Sriep,
I don't think this is an issue with our application. Most probably the external nodes have configured their Gateway to disable cross origin requests. This doesn't impact n2n requests because they don't include origin header and don't do explicit OPTIONS request. It would be better to inform all the node owner who want to be part of block explorer to allow cross-origin requests in their gateway.
A way to bypass this during development is to use origin/cors changer tool as specified by @Sriep. An alternative, would be to use a proxy that allows cross-origin requests, and proxies actual requests to respective nodes as a n2n request.

**Comment by guruhubb** [comment]
@anish-squareops can you enable this on 0miner/0prem and 0chain/blobber repo to allow for cors from explorer.

**Comment by anish-squareops** [comment]
@haule24hdev @guruhubb check https://0box.io/

**Comment by anish-squareops** [comment]
@guruhubb  Its enabled for 0miner, will fix it for 0chain and blobber
