### ISSUE TITLE
Failed to verify genesis dkg: ERROR: failed to verify dkg summary

### ISSUE THREAD

**Issue by anish-squareops** [0chain/0chain#329]
Miners are crashing with below logs:
```
panic: Failed to verify genesis dkg: ERROR: failed to verify dkg summary: share unable to verify: 10eaa04395db4296ce9dd5d0e8a047393fdc051baaed850577429dc33ec5cf46
goroutine 1 [running]:
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0005cc000, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x7bf
go.uber.org/zap.(*Logger).Panic(0xc00026f260, 0xc000688140, 0x9b, 0x0, 0x0, 0x0)
	/go/pkg/mod/go.uber.org/zap@v1.10.0/logger.go:225 +0x7c
main.main()
	/0chain/go/0chain.net/miner/miner/main.go:251 +0x30cf
```

**Comment by anish-squareops** [comment]
Working commit : https://github.com/0chain/0chain/commit/f84a3d897d33461ae708c3416424ad78d383a9ff

**Comment by bbist** [comment]
The magicblock generation code was using `SerializeToHexStr()` method instead of `GetHexString()`, which was causing the changes in https://github.com/0chain/0chain/commit/ff88415d84b9cac81c6cbbf0c56577ee2d071ff8 to work improperly.
Therefore, 
1. `SerializeToHexStr()` was updated to `GetHexString()` in 0chian.net/chaincore/block/magicBlock/main.go.
2. New MagicBlock and DKG summaries are created with new magicblock generator.
