### ISSUE TITLE
Do not verify block if the VRF shares have not reached threshold

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#601]
A miner should not verify a block if it does not have enough VRFShares consensus for the RRS of the block.

Check details here: https://0chain.slack.com/archives/C01V27E2Z9N/p1634872520004600

**Comment by peterlimg** [comment]
The chain moves pretty slow after adding the logic to do not verify block if the VRF shares have not reached threshold. Sometimes it takes more than 10 seconds to move on to the next round. The chain moves slow because some miners could not verify the proposed block as they have not yet collect enough VRF shares. Because they could not verify the block, they would not send out the block verification tickets, therefore, slowed down the tickets collection. This could be even worse if the miner has limited CPU resources and when the CPU is busy, they could drop the VRF share messages due the timeout for validating N2N messages. 

We can fix the above issue by adding VRF shares to the verify block message, the miner who sends out the verify block message must already have collected enough VRF shares. So when a miner received a proposed block for verification, we can verify and merge the VRF shares from the message into local round. Only when the VRF shares are valid and reached the threshold, will the miner move to next step to do the block verification. I did some tests, and this worked pretty well, basically the chain moves the same speed as before. 

What do you think @guruhubb @dabasov

**Comment by dabasov** [comment]
@peterlimg do you have any idea, why network started to move slowly? in theory majority of miners should move at the network speed, since they all reach threshold (well it is the way to find out what is the network speed). 
I want to say, that couple of slow miners must not affect the majority and they have to move fast despite of 1/3 of delayed or even Bizantine. 

Your solution can work but for me it can be excessive and bring network overhead. With such approach we try to solve network issues, in fact we resend messages that was not received earlier, well, for protocol to work well we still need synchrony assumption.

I'm seriously worried not even about network traffic, but that this "slowness" can hide some other serious issues, which we can hide, for example some networking bugs  (a lot of network failures we talk with @guruhubb recently) and so on.

Resending messages in general can be reasonable, we can piggy back even previous blocks, to reduce number of fetching requests for example, and it can be good way to sacrifice some network traffic for latency. Just suggest to investigate this slowness issue.
