### ISSUE TITLE
Could not reach to latest finalized block

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#623]
On [hero](http://216.218.228.197:7071/_diagnostics) network, we can see errors of `could not reach to latest finalized block` sometimes, and when this happens, the `latest finalize block` would not be updated until round timeout and restarted. 
```
...skipping...
2021-10-30T13:02:01.395Z        DEBUG   chain/protocol_round.go:206     finalize round - could not reach to latest finalized block      {"round": 195, "lfb
 round": 195, "prev lfb round": 177, "lfb block": "89eadecca269a6f0b907ab0ef2fd692a594e36f46f53e14e995bf290b14f8cb9"}
```
We don't see this error before, because previously, in round finalize process, we didn't check if the current finalizing block's previous block is the `latest finalize block`. 

When this error happens, it could be either a) the current finalizing block is incorrect, or b) the latest finalized block is incorrect. Both need to be handled correctly.

@guruhubb what do you think.

**Comment by guruhubb** [comment]
Why do we need to check this ?` if the current finalizing block's previous block is the latest finalize block.`
During the finalize process, we can select r-1 or r-2 block to start the finalization process, which is essentially walking back from that block and making sure the heaviest chain is the winner. 
But there should be a LFB with the miner, and if its not updated or not there for whatever reason (say miner was down for some time or did not receive notarized blocks because its CPU was busy or network was down), then the miner should get the LFBs from other miners or shaders.  cc @dabasov

**Comment by peterlimg** [comment]
@guruhubb you're right, we don't need to do the check.

**Comment by dabasov** [comment]
In theory, this kind of checks can exist and can be useful. If disaster happens ( more than 1/3 of miners are malicious for example) it is useful to know this fact for the honest miner. Such situations rarely if ever are handled in blockchains, i think because there are not much honest miner can do, probably stop processing. 
In my opinion, it is too much to fetch missing blocks here because of such rare situation, so agree with @guruhubb we can eliminate this check.
