### ISSUE TITLE
Add merkle proofs for state entities

### ISSUE THREAD

**Issue by dabasov** [0chain/0chain#631]
To make proper validation of state entities: `*state.PartialState`, `*block.StateChange` we should add Merkle proofs state nodes for entity transfer.
At the moment we can't validate state we receive from third party.

**Comment by peterlimg** [comment]
Yes, the `*state.PartialState` does not have proper validation, people can fake the state changes as long as they can connect to the right `root`. We should be able to do the validation simply by computing the hash of node and compare to its parent's children keys from bottom to root. However, since the `UpdateVersion()` function does not update the key of a node after changing the `version` field, so basically we can not do the validation in that way. 

We may need another Merkle tree and its root may different from the MPT root for the partial state, or we can force the `UpdateVersion()` to update the key and regenerate the MPT root.

**Comment by dabasov** [comment]
I didn't get it, can't we get merkle proof of a node in current MPT?

**Comment by peterlimg** [comment]
Oh, my mistake, I thought the `UpdateVersion()` would change the node's hash key, but it will not. The encode process does not touch the `version` field, so even we changed the version of a node, the `GetHashBytes()` of a node will still return the same key. So it should be easy to validate the acquired state changes. Let me do a quick fix.

**Comment by peterlimg** [comment]
The state changes and partial state are actually validated in `ComputeProperties()` when it was decoded in `FromJSON()` function. So we should be fine with the current implementation.
