### ISSUE TITLE
Goroutine leaks issue on large network

### ISSUE THREAD

**Issue by peterlimg** [0chain/0chain#635]
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/54137706/140011433-6553a6f5-1c77-4b63-a9d3-0a2f02c3f3d9.png">

The goroutines number is really high comparing to those normal miners. And the LFB is about 2000 rounds behind the current round. The round restart times is 0, because it continually receive `notarization` messages, which keeps the current round being updated, therefore, the round timeout process would not be triggered. 

Instead of waiting for the miner to restart round to pull the LFB from sharders, or syncing blocks from the far away behind LFB, we need to pull LFB from sharders to do a quick update of the LFB. Otherwise, the miner may never be able to recover from the high goroutines. 

The problem is when should we force update the LFB from sharders, as each time we update the LFB from sharders, we may create a block gap. One possible condition is when the miner finds that its local LFB is 50% of the `config.prune_below_count` rounds behind the LFB ticket (get from sharder), or other percentage maybe, need test to confirm.

**Comment by peterlimg** [comment]
In addition to the LFB updating, we need to limit the max goroutine numbers for handling the `VerifyBlock` message. From the goroutine pprof as shown below, it could be found that the `HandleVerifyBlockMessage` used lots of goroutines, we should not create a goroutine for each `VerifyBlock` message the miner received. Instead, we need to queue the messages, and have limited `N` workers to get message from the queue and process them. 
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/54137706/140048305-0118c819-9dce-425c-b8bc-1e6e5f8ade8e.png">

**Comment by dabasov** [comment]
>  And the LFB is about 2000 rounds behind the current round. The round restart times is 0, because it continually receive notarization messages, which keeps the current round being updated, therefore, the round timeout process would not be triggered.

Why can't we collect enough notarizations (r0) and start next round(r0 + 1) to synchronize with network and fetch missing blocks later, why do we need restart round here?

Well, I do not think that pooling goroutines is the right approach. Look at go docs [here](https://golang.org/doc/faq#goroutines) 

> When a coroutine blocks, such as by calling a blocking system call, the run-time automatically moves other coroutines on the same operating system thread to a different, runnable thread so they won't be blocked. The programmer sees none of this, which is the point. The result, which we call goroutines, can be very cheap: they have little overhead beyond the memory for the stack, which is just a few kilobytes.

> The CPU overhead averages about three cheap instructions per function call. It is practical to create hundreds of thousands of goroutines in the same address space.

Till goroutines a terminated properly it is not a problem to have a lot of them. And their execution seems to be pooled on threads already by go scheduler. 

The problem you shed light on is in broken logic of message processing, my opinion is we should do something with logic and not how goroutines are run:
> The round restart times is 0, because it continually receive notarization messages, which keeps the current round being updated, therefore, the round timeout process would not be triggered.
We should probably discard this messages or terminate already running goroutines via context.cancel to free resources.

**Comment by peterlimg** [comment]
> Why can't we collect enough notarizations (r0) and start next round(r0 + 1) to synchronize with network and fetch missing blocks later, why do we need restart round here?

We do start next round(r0+1) when received notarization message for (r0), but notarization message does not have the block data itself, it only has brief block info such as block hash and tickets for verification. We will need to pull the block from remote if the miner does not have it locally. For miner who has block lag, most of the time, it does not have the block locally of the received notarization message, it has to fetch the block from remote so that it can has block in round (r0), then start the next round (r0+1). So there's no 'fetch missing blocks later', as almost every notarization block is 'missed'.  

`LFB` updating is another progress, we should avoid updating the `LFB` outside the `finalize round` process as much as possible, otherwise block gaps would be created.

**Comment by peterlimg** [comment]
> Till goroutines a terminated properly it is not a problem to have a lot of them. And their execution seems to be pooled on threads already by go scheduler.

The high number of goroutines is not a problem itself, as goroutine are cheap. But the processes that are running on the goroutines is the problem, especially when miners' CPU resources are limited. Image that we have thousand of goroutines that are stuck on doing block verifying due to the CPU resources starvation, there's no `different, runnable thread so they won't be blocked` the operation system could schedue to. 

Another problem is due to CPU resources starvation, it's very slow for a miner to do block verification, and it can never finish all of these thousand pooled verification requests on the goroutines. Also, the verified blocks are basically useless, becuase the chain may have moved far away ahead of the verified block already. Despite the heavy CPU work on the block verification, there are other places that need CPU resources, such as notarization block process, VRF share verifying, etc. So, basically, we have to limit the goroutines for block verification.

**Comment by dabasov** [comment]
> We do start next round(r0+1) when received notarization message for (r0), but notarization message does not have the block data itself, it only has brief block info such as block hash and tickets for verification. We will need to pull the block from remote if the miner does not have it locally. For miner who has block lag, most of the time, it does not have the block locally of the received notarization message, it has to fetch the block from remote so that it can has block in round (r0), then start the next round (r0+1). So there's no 'fetch missing blocks later', as almost every notarization block is 'missed'.

Correct, but we don't need to execute this block in general, since it is verified already by honest majority of miners, we can delay its execution or move it to background, transfer to the next round and go on following the protocol at speed of network. Fetching of this block should be faster than round execution, since miner will need 2δ (2 latency) time against (5δ + Δ) (5 latency + delta) needed for round.
We can parallelize transactions execution of block with insufficient resources, but it won't help obviously. We can think about giving up execution of such blocks for slow nodes at all, and work with partial states later on, it worth thinking about, don't know will it solve concrete problem. 

I want to say, that the problem is not in way we execute work, but in protocol logic. In general it is near impossible to protect distributed system against dDos attack, we usually can only remove attacker from the network with ban, rating or similar approach.

Look, limiting the number of routines won't add any resources which we starve, everything we will do with goroutines pooling is to queue messages. The problem is hidden in the amount of work in time, to solve it we have to reduce it in any way possible: 
- cancel running tasks as soon as we understand that these tasks are not needed anymore 
- filter tasks before starting
- add more resources to slow nodes
- slow down processing of all network with reasonable delay, so slow nodes could run all the tasks in time.
 
Limiting the number of routines or trying to manage execution can help sometimes, but can't solve the problem. In theory, even if it helps, it helps only for concrete network setup, if we change configuration or amount of resources dedicated for each node it won't work. 
I looked at big cluster when this problem occurred, reducing of number of transactions in block solved it. There was couple of nodes with low resources dedicated to them, so they failed processing of large blocks.
