### ISSUE TITLE
Unit-tests for Sharder params: proximity_scan and deep_scan

### ISSUE THREAD

**Issue by moldis** [0chain/0chain#738]

**Comment by platsko** [comment]
[The parameters report](https://drive.google.com/file/d/1aEGSEfRlEfmQeo9kVw9hKtrsTywwN83f/view?usp=sharing)

**Comment by platsko** [comment]
There is unclear implementation that reads the configuration parameters of deep_scan and proximity_scan, since there is a conflict - proximity_scan just overwrites of deep_scan parameters.

![image](https://user-images.githubusercontent.com/4425317/145205405-6a50d987-9a78-4992-8e8c-56724533f8b1.png)

I think it is not okay.
@moldis @guruhubb what do you think?

**Comment by moldis** [comment]
<img width="855" alt="image" src="https://user-images.githubusercontent.com/2959408/145353881-fc102060-4a4e-46d1-8446-a885ba836b55.png">

@platsko

**Comment by platsko** [comment]
@moldis @guruhubb 
Have no idea what functions can be covered with testing, so I think we can close the ticket because of reasons above.

**Comment by guruhubb** [comment]
The proximity and deep scan cannot run together. So in the code, we should have a check for such.
Proximity scan is for sharders that have gone down or bad network connection for a few hours.
Deep scan is for new sharders joining. 
@platsko @moldis is it clear now?

**Comment by jkrus** [comment]
@guruhubb You mentioned that the proximity_scan options have been tested. Can you tell in which branch this is described?

**Comment by jkrus** [comment]
Added unit tests
https://github.com/0chain/0chain/pull/1082

**Comment by dabasov** [comment]
closed in https://github.com/0chain/0chain/pull/1082
